# Generated by Django 4.1.1 on 2024-01-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='created_bt',
            new_name='create_bt',
        ),
    ]
